# Generated by Django 4.2.5 on 2023-09-21 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0002_category_contact_picture_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
